services:
  fastapi:
    build: .
    container_name: yamama-api
    expose:
      - "8080"
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: yamama-nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./.well-known:/var/www/html/.well-known:ro
    depends_on:
      - fastapi
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge