openapi: 3.0.3
info:
  title: Yamama Chatbot API
  version: 1.0.0
  description: |
    The Yamama Chatbot API processes user input and provides an AI-generated response, 
    along with optional map actions, coordinates, region/city/district information, 
    and data visualizations for display on a map.

paths:
  /chat:
    post:
      summary: Get chatbot response and map instructions
      operationId: getChatbotResponse
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sessionId
                - inputMessage
              properties:
                sessionId:
                  type: string
                  description: Unique ID for the current chat session
                  example: "abc123-session"
                inputMessage:
                  type: string
                  description: User's message to the chatbot
                  example: "Show me the population distribution"
      responses:
        '200':
          description: Successful chatbot response
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessionId:
                    type: string
                    description: Session ID for the current chat session
                    example: "abc123-session"
                  outputMessage:
                    type: string
                    description: AI-generated response to the user's message
                    example: "Here is the population distribution by region."
                  mapAction:
                    type: string
                    description: Action to perform on the map
                    enum: [REFRESH, ZOOMIN, ZOOMOUT, MOVE]
                    example: "REFRESH"
                  mapCoordinates:
                    type: object
                    description: Coordinates for map focus
                    properties:
                      latitude:
                        type: number
                        format: float
                        example: 24.7136
                      longitude:
                        type: number
                        format: float
                        example: 46.6753
                  regionId:
                    type: string
                    nullable: true
                    description: ID of the selected region (nullable)
                    example: "r_01"
                  cityId:
                    type: string
                    nullable: true
                    description: ID of the selected city (nullable)
                    example: "c_05"
                  districtId:
                    type: string
                    nullable: true
                    description: ID of the selected district (nullable)
                    example: "d_12"
                  mapData:
                    type: object
                    nullable: true
                    description: JSON object containing data to visualize on the map
                    oneOf:
                      - title: District-level data
                        type: object
                        required: [districts, title]
                        properties:
                          districts:
                            type: object
                            additionalProperties:
                              type: number
                            example:
                              d_01: 100
                              d_02: 132
                              d_03: 65
                          title:
                            type: string
                            example: "Average Age"
                      - title: Region-level data
                        type: object
                        required: [regions, title]
                        properties:
                          regions:
                            type: object
                            additionalProperties:
                              type: number
                            example:
                              r_01: 150
                          title:
                            type: string
                            example: "Population"
                      - title: City-level data
                        type: object
                        required: [cities, title]
                        properties:
                          cities:
                            type: object
                            additionalProperties:
                              type: number
                            example:
                              c_01: 75
                              c_02: 120
                          title:
                            type: string
                            example: "Education Index"
                  chartData:
                    type: object
                    nullable: true
                    description: Chart data for visualization
                    properties:
                      chartType:
                        type: string
                        description: Type of chart to display
                        example: "bar"
                      chartTitle:
                        type: string
                        description: Title of the chart
                        example: "Population Distribution by Region"
                      xAxisTitle:
                        type: string
                        description: Title for the X-axis
                        example: "Regions"
                      yAxisTitle:
                        type: string
                        description: Title for the Y-axis
                        example: "Population (millions)"
                      x:
                        type: array
                        items:
                          type: string
                        description: X-axis data points
                        example: ["Riyadh", "Makkah", "Eastern Province", "Asir", "Jazan"]
                      y:
                        type: array
                        items:
                          type: number
                        description: Y-axis data points
                        example: [8.2, 7.1, 4.9, 2.2, 1.6]
                      dataLabel:
                        type: string
                        description: Label for the data series
                        example: "Cities"
        '400':
          description: Invalid request
        '500':
          description: Server error

components:
  schemas:
    Coordinates:
      type: object
      properties:
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float